### ISSUE TITLE
Any error and it doesn't work with the command /daily.

### ISSUE THREAD

**Issue by Andreeiii11** [Elipse458/el_daily_rewards#4]
Any error and it doesn't work with the command /daily.

**Comment by Andreeiii11** [comment]
![image](https://user-images.githubusercontent.com/41338573/83653270-dccb4d80-a5bb-11ea-96f0-ba07b1e025d7.png)

**Comment by Elipse458** [comment]
i stopped supporting this release a long time ago, try this one https://forum.cfx.re/t/re-release-esx-daily-rewards-updated-1-2-15-2-20/1016265
